README.md

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

Initial chapter outline

---

11.coreboot.u-root.systemboot/README.md

In the coreboot/LinuxBoot section: added further details for menuconfig options, and a couple of fixes

Added kernel build details for menuconfig

---

11.coreboot.u-root.systemboot/README.md

Added instructions for building the coreboot image for Qemu with our LinuxBoot payload

Added coreboot build instructions

---

11.coreboot.u-root.systemboot/README.md

Some important kernel features were missing from the documentation. Added here

Added a section about fundamental kernel features

---

10.u-root/README.md

Clean up references and some code

---

14.cpu/README.md
README.md

Add cpu chapter

---

10.u-root/README.md
11.coreboot.u-root.systemboot/README.md
7b.UEFI_Tool_Kit/README.md

Each chapter should have one where possible.
I am not sure the command is right.

Add a quick start section

---

7b.UEFI_Tool_Kit/README.md

the utk chapter is great, but the quickstart is a bit too long
for a quick glance.
So I am adding a synopsis section. Next will be a section
on the cleaner.

Add a synopsis section for utk

---

case_studies/TiogaPass/README.md

Signed-off-by: Johnny Lin <johnny_lin@wiwynn.com>

Update README.md for OCP TiogaPass

---

LICENSE

From https://choosealicense.com/licenses/cc-by-sa-4.0/
Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

Add Creative Commons License

---

coreboot.u-root.systemboot/README.md

Removed references to systemboot that is now merged in u-root.
fixes #35 
Signed-off-by: Andrea Barberio <insomniac@slackware.it>

[coreboot chapter] updated build instructions

---

README.md

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

Add github links in acknowledgments section

---

README.md
u-root/README.md

Signed-off-by: gmadrone <gmadrone@google.com>

Updating the u-root chapter and added a new table of contents.

---

SUMMARY.md
faq/README.md

with only one question for now, but well we need to start somewhere !

Adding FAQ section

---

README.md

Signed-off-by: gmadrone <gmadrone@google.com>

Fixed link to implementation chapter.

---

coreboot.u-root.systemboot/README.md

Update the u-root URL to the github repo.

Update u-root URL

---

u-root/README.md

There is a duplicate paragraph with respect to lines 254-256.
Signed-off-by: Patrik Tesarik <mail@patrik-tesarik.de>

Change u-root chapter and remove a duplicate

---

implementation/README.md

Fleshed out details of this chapter.

Add further detail to the Implementation chapter

---

cpu/README.md

Add a note on CPU_NAMESPACE and docker containers

---

cpu/README.md

Add notes on new -fstab option

---

cpu/README.md

Update cpu documentation

---

getting_started/README.md

Fix up the getting started README.md

---

utilities/README.md

We have a bunch of utilities, quite some already documented here, but not referenced from the README's ToC.
Plus, an overview would be nice. This is a half-issue-PR. :)

WIP: chapter on utilities

---

implementation/README.md

implementation: clean-up using mdl

---

intro/README.md

Removed duplicate sentence in intro README.

fix: remove duplicate in intro

---

src/history.md

references and rewording around BIOS

---

src/SUMMARY.md
src/tools-evaluation.md
src/use-cases.md

draft chapters on use cases and tools evaluation

---

.github/workflows/gh-pages.yml
.gitignore
Makefile
README.md
book.toml

- CI: upgrade to checkout@v4
- set up Mermaid integration
- CI: Switch to jontze's GitHub action

Set up mermaid, but with jontze's action 🧜‍♀️

---

.github/workflows/gh-pages.yml

https://github.com/Michael-F-Bryan/mdbook-linkcheck?tab=readme-ov-file#continuous-integration

CI: fix up deployment after linkcheck introduction

---

.github/workflows/gh-pages.yml
Makefile
README.md
i18n.sh

I18n rework
